language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: kzWTcNAe9cifYxxgczYF35H1VC0lYqX5FHTSv/miIdxERqoXU5vwivR0uae16XZMDm2ibIIQ90LZQHvJpe/cSB7oeUV6YkcC6WoyYmX8VfjJktC9sdxePgIpx+vymf/Mh+2rNvxaiADTf2LUIiJJY6M8MU4RfIryAUvB0qtG9+BYYpAQJ85r59YF1iq70rMh2+wiO1EJCQXeCQ7t3MMvjoOmgQhgDrOZzCwTGz362Akp1fA45SqruRQrpSIUcl6QYye0QM8oEHGy++ReO3WXxT+aCkmdNbSQNYe8OFra8Sox189b/cNsIoWDVcNWwWspUO/M5gvge0005CIjngObzoFPUz8Wq7cFLx8sG78OQGJXlEPSS2Yig4jnxOozJIadVAmArds7karpaJLqpWg8Y+aZcO+GlRXWjMtNhGYRGfgEWVa84vDSD3yVW2Ioao/6/p0LdAskuznqrd/jApr196cwK3izpLlQrwqa5vk3aYlpqGgxlpITzvsImCD+N05VsMpITpw6hX8dutYkyCmPSn4S9fsKVtyxVU08ecDpo18SXX2eKtfiHKVO87Q2VFh2qr9GduPinL2WbdGYv4eKmzye0ZiLS/yI1A8Pe0PEEmuQLfYBCZzLi2dWHfPKBzCoTybGoT9wbAuFpKq/Kz1dPjXkZZgEPO/jzDj+a8P7gdo=
  app: pure-depths-26494
  on:
    repo: thinkful-ei21/leo-test-integration-testing-mongoose
    branch: feature/with-tests
